language: node_js

node_js:
  - 6.3.1

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: npm test

notifications:
  email:
    on_success: never
    on_failure: change
